services:
  db:
    image: mariadb:10.7
    container_name: wp_db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env
    networks:
      - wpnet

  wordpress:
    image: wordpress:php8.1-fpm
    container_name: wp_app
    restart: always
    depends_on:
      - db
    volumes:
      - wp_data:/var/www/html
    env_file: .env
    networks:
      - wpnet

  nginx:
    image: nginx:latest
    container_name: wp_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - wp_data:/var/www/html
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - wordpress
    networks:
      - wpnet

  certbot:
    image: certbot/certbot
    container_name: wp_certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'"
    networks:
      - wpnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: c%FzgCfU8eo%caxs
    ports:
      - "8080:80"
    networks:
      - wpnet

volumes:
  db_data:
  wp_data:

networks:
  wpnet:
